version: '3.8'

services:
  db:
    image: postgres:16
    container_name: app_postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app_nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://appuser:password123@db:5432/appdb?schema=public"
    depends_on:
      - db

volumes:
  pgdata:
